"""
=============================================================
Receiver Operating Characteristic (ROC) with cross validation
=============================================================

Example of Receiver Operating Characteristic (ROC) metric to evaluate
classifier output quality using cross-validation.

ROC curves typically feature true positive rate on the Y axis, and false
positive rate on the X axis. This means that the top left corner of the plot is
the "ideal" point - a false positive rate of zero, and a true positive rate of
one. This is not very realistic, but it does mean that a larger area under the
curve (AUC) is usually better.

The "steepness" of ROC curves is also important, since it is ideal to maximize
the true positive rate while minimizing the false positive rate.

This example shows the ROC response of different datasets, created from K-fold
cross-validation. Taking all of these curves, it is possible to calculate the
mean area under curve, and see the variance of the curve when the
training set is split into different subsets. This roughly shows how the
classifier output is affected by changes in the training data, and how
different the splits generated by K-fold cross-validation are from one another.

.. note::

    See also :func:`sklearn.metrics.auc_score`,
             :func:`sklearn.model_selection.cross_val_score`,
             :ref:`sphx_glr_auto_examples_model_selection_plot_roc.py`,

"""

import numpy as np
from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier


###############################################################################
# Classification and ROC analysis

# Run classifier with cross-validation and plot ROC curves
random_state = np.random.RandomState(0)
cv = StratifiedKFold(n_splits=3)
classifier = RandomForestClassifier(n_estimators=20,n_jobs=4,class_weight='balanced',random_state=random_state)

colors = cycle(['cyan', 'indigo', 'seagreen', 'yellow', 'blue', 'darkorange'])
lw = 2


###############################################################################
# Data IO and generation

for n, color in zip(range(3,7), colors):
    N=2*n+1
    mean_tpr = 0.0
    mean_fpr = np.linspace(0, 1, 100)
    filename=''.join(['trainensemdata_',str(N), '.csv'])
    #filename=''.join(['trainensemrawdata_',str(N), '.csv'])
    cv_data=open(filename,'rt')
    cv_data=np.loadtxt(cv_data,delimiter=",")
    cv_data=np.nan_to_num(cv_data)
    X=cv_data[:,:pow(N,2)*4]
    y=cv_data[:,-1]
    n_samples, n_features = X.shape
    for (train, test) in cv.split(X, y):
        probas_ = classifier.fit(X[train], y[train]).predict_proba(X[test])
    # Compute ROC curve and area the curve
        fpr, tpr, thresholds = roc_curve(y[test], probas_[:, 1])
        mean_tpr += interp(mean_fpr, fpr, tpr)
        mean_tpr[0] = 0.0
        roc_auc = auc(fpr, tpr)
        #plt.plot(fpr, tpr, lw=lw, color=color,
        #      label='ROC fold %d (area = %0.2f)' % (i, roc_auc))

# i += 1
        #plt.plot([0, 1], [0, 1], linestyle='--', lw=lw, color='k',
# label='Luck')

    mean_tpr /= cv.get_n_splits(X, y)
    mean_tpr[-1] = 1.0
    mean_auc = auc(mean_fpr, mean_tpr)
    plt.plot(mean_fpr, mean_tpr, color=color,
         label='Mean ROC (area = %0.2f) N = %d' % (mean_auc, N), lw=lw)

plt.xlim([-0.05, 1.05])
plt.ylim([-0.05, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC evaluation')
plt.legend(loc="lower right")
plt.show()
